### ISSUE TITLE
Error when running uno watch

### ISSUE THREAD

**Issue by Hanksha** [zposten/unorepo#9]
Hi,

When I run `uno watch` I'm getting the following error:

```

(node:5143) UnhandledPromiseRejectionWarning: TypeError: Non-string provided as watch path: ,,,,,,,
    at FSWatcher.add (/Users/<masked>/.config/yarn/global/node_modules/chokidar/index.js:604:11)
    at Object.exports.watch (/Users/<masked>/.config/yarn/global/node_modules/chokidar/index.js:746:33)
    at /Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:21086
    at s (/Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:12200)
    at Generator._invoke (/Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:11988)
    at Generator.t.(anonymous function) [as next] (/Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:12622)
    at n (/Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:18795)
    at c (/Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:18997)
    at /Users/<masked>/.config/yarn/global/node_modules/unorepo/dist/unorepo.js:2:19056
    at new Promise (<anonymous>)
(node:5143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

OS: macOS
npm: 6.11.3
yarn: 1.21.1

**Comment by 0livare** [comment]
Hi @Hanksha, can you provide an example repo that reproduces this problem?

**Comment by 0livare** [comment]
Closing due to no response
